### ISSUE TITLE
Remaining time from the slicer

### ISSUE THREAD

**Issue by zoltanf** [mriscoc/Marlin_Ender3v2#152]
### Description

When enabling the remaining time generation in slicer (command M73), the value is shown on the screen, but it jumps between the slicer and the calculated time. It would be great to show only the slicer estimated remaining time when it's present in the gcode.

Would like to use this opportunity to thank you developing/maintaining this firmware branch, the actual usability of the printer is raised to a new whole level with this.

### Steps to Reproduce
1. Check the option "Supports remaining times" under printer settings in prusa slicer or super slicer. 
2. Generate a gcode file and run the print. Observe the displayed remaining time. In gcode it is updated approximately every minute.

**Expected behavior:**
Show slicer estimated remaining time, as it is usually more precise.

**Actual behavior:**
Remaining time switching on display between the firmware calculated remaining time and the slicer remaining time from gcode.

#### Additional Information
Pictures bellow. Please excuse the quality. The shots were taken in a span of a single minute during printing:
![IMG_20211121_231804](https://user-images.githubusercontent.com/1464667/142816393-950509ce-2b47-45f1-8b0b-be38a27f0296.jpg)
![IMG_20211121_231830](https://user-images.githubusercontent.com/1464667/142816402-4bef97b7-9b07-494f-aa06-611822573ff6.jpg)

PrusaSlicer setting (same result verified in SuperSlicer):
![Screenshot 2021-11-22 at 07 46 16](https://user-images.githubusercontent.com/1464667/142816524-e3149f01-6a80-4502-8168-30cc69459a82.png)

**Comment by mriscoc** [comment]
Thank you for your report, we will investigate about it.

**Comment by zoltanf** [comment]
Printing via µSD card.

**Comment by mriscoc** [comment]
The printer updates the remaining time in an independent way when the print is via µSD. The only solution that I see for this behavior is to disable the internal update of the remaining time when the first M73 R### is received.

**Comment by zoltanf** [comment]
I think that is a reasonable solution.
