### ISSUE TITLE
Load Filament UX Issue

### ISSUE THREAD

**Issue by stonie08** [mriscoc/Marlin_Ender3v2#173]
### Description
The "Load Filament" functionality purges the remaining filament and afterwards asks if one wants to "purge or continue". The options given are "Confirm" or "Continue", which has resulted in unintended addition purges.

### Steps to Reproduce

1. Unload the filament and load the new one
2. Go to Control -> Filament Management -> Load Filament
3. Decide wheter Confirm or continue have the desired effect

**Expected behavior:** [What you expect to happen]
I'd expect the two options to be "purge" and "continue/confirm" or similarly to clearly indicate the behavior.

**Actual behavior:** [What actually happens]
Because the filament has already been purged once, "continue" suggests that the the printer should continue to purge, because that was its last action. Confirm on the other hand indicates the end of some process. The printer only asks wheter to "Purge or Continue" which isn't explicitely reflected in the buttons.

**Comment by mriscoc** [comment]
We are limited by the assets on the DWIN display firmware, currently the only button faces available are: `No longerprompt`, `Continue`, `Cancel` and `Confirm`. For add more button faces it is possible to do a custom asset but I prefer to maintain compatibility with the stock display firmware. The drawing of basic buttons is in the ToDo list, but the display is some slow.
