### ISSUE TITLE
Probe Failure during any probing over 6x6.

### ISSUE THREAD

**Issue by DralrinResthal** [mriscoc/Marlin_Ender3v2#181]
Any time I try to create a new mesh using a probing of over 6x6, my probe get's through most of the bed without issues until the back right corner. It will crash the printhead into the bed without deploying the probe, and then display a "Probing Failed. Rewiping" error message. 

Using pre-compiled binary.

**Comment by mriscoc** [comment]
If you have a CRTouch check this: https://github.com/mriscoc/Marlin_Ender3v2/wiki/3D-BLTouch#notes-about-cr-touch

**Comment by DralrinResthal** [comment]
Hey I'll take a look and try this, thanks!
I'll close this out if it works.

**Comment by mriscoc** [comment]
I'm closing this issue because there isn't more feedback.
