### ISSUE TITLE
[Wiki] 2-char mistype in "How-to-install-the-firmware"

### ISSUE THREAD

**Issue by spencjon** [mriscoc/Marlin_Ender3v2#183]
### Description
SD Allocation specified as 4069 rather than 4096 

### Steps to Reproduce
https://github.com/mriscoc/Marlin_Ender3v2/wiki/How-to-install-the-firmware#manual-install

Point 1: "Insert a blank and MBR, FAT32 and 4069 allocation unit formatted µSD in your PC/Mac"
should be: 

4069 should be 4096

**Comment by mriscoc** [comment]
Oh! Thank you for pointing out this error!
