### ISSUE TITLE
Cura Thumbnail change background color

### ISSUE THREAD

**Issue by OllisGit** [mriscoc/Marlin_Ender3v2#206]
Thanks a lot for your wiki-post:
https://github.com/mriscoc/Marlin_Ender3v2/wiki/How-to-generate-a-gcode-preview#octoprint

Do you think it is possible to "pre define" the background color of the thumbnail?

In the past I received this issue: https://github.com/OllisGit/OctoPrint-PrintJobHistory/issues/160
And for the CURA-Plugin I was able to fix it, but with your script it looks like that it is always black.

**Comment by mriscoc** [comment]
Currently, the background color of the thumbnail is controlled by Cura, you can use the original plugin `Create Thumbnail` for create a PNG with transparent background. Also, you could programmatically change the background in the script if you convert the image to a bitmap and replace the black pixels with another color.
