### ISSUE TITLE
Repeating manual level after homing shifts the height of the corners

### ISSUE THREAD

**Issue by net147** [mriscoc/Marlin_Ender3v2#208]
If you have a bed where the center is lower than the corners, then doing manual leveling of corners, homing and then starting manual level again shows the height of the 4 corners change by the difference in height between the center and the corners.

I believe Jyers firmware handles this by also probing the 4 corner points in addition to the center and offsetting the height measurements so that repeating homing and manual leveling result in the knobs repeatedly being adjusted in one direction.

**Comment by mriscoc** [comment]
Please check: https://github.com/mriscoc/Marlin_Ender3v2/wiki/Manual-leveling-(leveling-bed-corners)-menu
