### ISSUE TITLE
The script to embed the images in the gcode does not work in macOS 12.1 (Prusa Slicer)

### ISSUE THREAD

**Issue by sronco01** [mriscoc/Marlin_Ender3v2#210]
### Description
the script to embed the images in the gcode does not work in macOS 12.1 (with Prusa Slicer)

### Steps to Reproduce

1. [First Step]
<img width="1023" alt="Captura de Pantalla 2022-01-21 a la(s) 16 13 43" src="https://user-images.githubusercontent.com/96654390/150586712-748b7809-96d3-4a18-8b0c-00d657caf153.png">

2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by mriscoc** [comment]
You need to install Python3 and use the python 3 executable
