### ISSUE TITLE
Print Timer and % not displayed

### ISSUE THREAD

**Issue by Str33tfight3rZ1000** [mriscoc/Marlin_Ender3v2#56]
Hello, I am using firmware version Beta-422-BLTouch5x5-20210529-040209
on my Ender3 V2.

 I print files via Octoprint. 
As soon as I have started a print, the menu opens with the time that has already passed, etc. But the process bar and the time that the print still requires does not run or is not displayed.

What can that be?

greeting
Chris

**Comment by mriscoc** [comment]
> Hello, I am using firmware version Beta-422-BLTouch5x5-20210529-040209
> on my Ender3 V2.
> 
> I print files via Octoprint.
> As soon as I have started a print, the menu opens with the time that has already passed, etc. But the process bar and the time that the print still requires does not run or is not displayed.
> 
> What can that be?
> 
> greeting
> Chris

Hi, please try the latest beta and follow this guide to print with Octoprint: https://github.com/mriscoc/Marlin_Ender3v2/wiki/Octoprint
