### ISSUE TITLE
Include Meatpack

### ISSUE THREAD

**Issue by thomasvt1** [mriscoc/Marlin_Ender3v2#63]
Hi,

Thanks for this great firmware! Altough this firmware uses a higher baud rate to communicate with the printer. Wouldn't using Meatpack also double the baud rate since in most cases it compresses the datarate bij 50%?

https://github.com/scottmudge/OctoPrint-MeatPack/

Thanks for your time!

**Comment by mriscoc** [comment]
Hi, more efficient is to double the baud rate, Meatpack can increase the error rate at that speed. Meatpack is not compatible with the binary file transfer protocol (BFT) that we use to update the firmware. Therefore, if we activate Meatpack, we must to decrease the communication speed and will not had the guarantee of get a 50% of compression, also we will lose the BFT compatibility.

**Comment by thomasvt1** [comment]
Makes sense! Thanks
