### ISSUE TITLE
print size is wrong: firmware says 230 by 230 when it should actually be 220 by 220

### ISSUE THREAD

**Issue by LordOfDeadbush** [mriscoc/Marlin_Ender3v2#68]
### Steps to Reproduce

1. try to print something
2. the build vol will be wrong so it will try to print off the bed

Beta-422V6-BLTouch-20210623-163655

**Comment by mriscoc** [comment]
The bed size of the Ender 3v2 is 235mm x 235mm and the printable area is 230mm x 230mm, also, if you want, you can change the printable area in Control / Physical Settings

![](https://raw.githubusercontent.com/mriscoc/Marlin_Ender3v2/Ender3v2-Released/screenshots/physical_settings.jpg)
