### ISSUE TITLE
Wrong temperatures when resuming paused print

### ISSUE THREAD

**Issue by AdamWP** [mriscoc/Marlin_Ender3v2#76]
When pausing, purging, and resuming a print the nozzle temperature dropped to 185 and bed to 0 and did not come back up to the previous temperature.

**Comment by njmV** [comment]
Same here. Temperature drops to the minimum extrude temperature of 185º and does not resume to the previous printing one. I always have to manual “fix it”.

**Comment by mriscoc** [comment]
Thank you for your report, I will to investigate.

**Comment by CyJaxX** [comment]
To reproduce this problem:
During printing, select pause and then confirm. Wait for printer to start cooling, then click to heat and resume printing. The nozzle temp will be set at 185 and the bed at 0.
The problem also occurs if the advanced pause is triggered by the filament runout sensor.

**Comment by mriscoc** [comment]
> To reproduce this problem:
> During printing, select pause and then confirm. Wait for printer to start cooling, then click to heat and resume printing. The nozzle temp will be set at 185 and the bed at 0.
> The problem also occurs if the advanced pause is triggered by the filament runout sensor.

There is an Advanced pause (Change Filament) on Tune menu.

**Comment by mriscoc** [comment]
> When pausing, purging, and resuming a print the nozzle temperature dropped to 185 and bed to 0 and did not come back up to the previous temperature.

The last experimental version is under test and fixed that issue.
