### ISSUE TITLE
Beta-427-BLTouch-20210714-144215.bin not flashing

### ISSUE THREAD

**Issue by vishusheelwant** [mriscoc/Marlin_Ender3v2#79]
when i tried to flash Beta-427-BLTouch-20210714-144215.bin on ender 3 v2 motherboard is 4.2.7 it shows blank screen.

**Comment by mriscoc** [comment]
> when i tried to flash Beta-427-BLTouch-20210714-144215.bin on ender 3 v2 motherboard is 4.2.7 it shows blank screen.

Try to use other µSD card, formar the card to FAT32. More info here: https://github.com/mriscoc/Marlin_Ender3v2/wiki/How-to-install-the-firmware
There is an updated version right now.

**Comment by vishusheelwant** [comment]
the newer .bin worked like a charm..
appreciate your work..
